export interface Project {
  id: string;
  name: string;
  description: string;
  longDescription?: string;
  topics: string[];
  language: string;
  category: 'ai' | 'web' | 'games' | 'creative' | 'personal';
  links: {
    demo?: string;
    github?: string;
    video?: string;
  };
  images?: {
    gallery?: string[];
  };
  featured?: boolean;
  status?: 'completed' | 'in-progress' | 'coming-soon';
  highlights?: string[];
}

export const projects: Project[] = [
  {
    id: 'modelviz',
    name: 'ModelViz',
    description: 'Compare AI models across providers with real-time metrics, cost analysis, and 3D visualisations.',
    longDescription: 'Interactive analytics platform for comparing AI models across OpenAI, Anthropic, Google (Gemini), and Perplexity. Test prompts across multiple models simultaneously, track usage metrics, analyse costs, and visualise API performance with an immersive cyberpunk-themed interface.',
    topics: ['Next.js', 'React 19', 'TypeScript', 'Three.js'],
    language: 'TypeScript',
    category: 'ai',
    links: { demo: 'https://modelviz.vercel.app/', github: 'https://github.com/ThomasJButler/ModelViz' },
    featured: true,
    status: 'completed',
    highlights: ['Multi-provider comparison (OpenAI, Anthropic, Google, Perplexity)', 'Real-time streaming with response metrics', 'Interactive 3D data visualisations', 'Cyberpunk-themed interface'],
  },
  {
    id: 'ai-code-generator',
    name: 'LangChain Code Generator',
    description: 'Full-stack code generation platform. Describe what you want, get production-ready code with tests and docs in 10 languages.',
    longDescription: 'Describe what you want in plain English and get production-ready code generated by GPT-4. Supports 10 languages: Python, JavaScript, TypeScript, Java, C#, Go, Rust, C++, Ruby, and Swift. Includes automatic test generation with framework detection and inline documentation. Built with LangChain, Python Flask backend, and React frontend.',
    topics: ['LangChain', 'GPT-4o', 'Python', 'React'],
    language: 'Python',
    category: 'ai',
    links: { github: 'https://github.com/ThomasJButler/AICodeGenerator', demo: 'https://theaigenerator.vercel.app/' },
    highlights: ['10 programming languages supported', 'GPT-4 powered code generation', 'Automatic test generation', 'Inline documentation generation'],
  },
  {
    id: 'sql-ball',
    name: 'SQL Ball Analytics',
    description: 'Football analytics platform converting natural language to SQL queries across 22 European leagues and 7,600+ matches.',
    longDescription: 'Ask questions about football in plain English, get SQL queries back. Works across 22 European leagues with 7,600+ matches. Features interactive dashboards with trends and anomaly detection, LangChain RAG backend for query parsing, and real-time visualisations via Chart.js. Built with Supabase, LangChain, OpenAI, and React.',
    topics: ['Supabase', 'LangChain', 'OpenAI', 'RAG'],
    language: 'Python',
    category: 'ai',
    links: { github: 'https://github.com/ThomasJButler/SQL-Ball', demo: 'https://sql-ball.vercel.app/' },
    highlights: ['Natural language to SQL conversion', '22 European leagues, 7,600+ matches', 'Interactive dashboards with anomaly detection', 'RAG-powered query parsing'],
  },
  {
    id: 'morpheus',
    name: 'Morpheus',
    description: 'Intelligent document Q&A with semantic search and source citations using RAG.',
    longDescription: 'An intelligent document reasoning system with a Matrix-themed interface. Upload your private documents and ask questions in natural language. Private by design — fresh Pinecone vector namespace per session, pay only for tokens used. Claude generates accurate answers from your specific documents with source citations.',
    topics: ['Pinecone', 'Anthropic', 'LangChain', 'FastAPI'],
    language: 'Python',
    category: 'ai',
    links: { demo: 'https://morpheusrag.vercel.app', github: 'https://github.com/ThomasJButler/Morpheus' },
    status: 'completed',
    highlights: ['Private by design — fresh namespace per session', 'Semantic search with Pinecone vectors', 'Source citations for every answer', 'Cost effective — pay only for tokens used'],
  },
  {
    id: 'reviewbot-protocol',
    name: 'ReviewBot Protocol',
    description: 'AI-powered GitHub PR review system with automated code analysis and intelligent feedback via custom dashboard.',
    longDescription: 'Full-stack AI code review system that automatically analyses GitHub pull requests and provides intelligent feedback. Catches common issues before human reviewers need to look at the code. Built with LangChain integration, LangGraph workflows for complex AI processing, GitHub webhook automation, and production-ready error handling. Demonstrates how tools like CodeRabbit work by building one from scratch.',
    topics: ['Next.js', 'LangGraph', 'FastAPI', 'GitHub API'],
    language: 'TypeScript',
    category: 'ai',
    links: { github: 'https://github.com/ThomasJButler/ReviewBot-Protocol' },
    highlights: ['Automated GitHub PR analysis', 'LangChain + LangGraph workflows', 'Webhook-driven reviews', 'Full-stack TypeScript/Python'],
  },
  {
    id: 'news-perspective',
    name: 'News Perspective',
    description: 'AI-powered news analysis that rewrites sensationalised headlines and generates TLDR summaries across US and UK sources.',
    longDescription: 'See the news, not the spin. Uses AI to rewrite sensationalised headlines to be calm and factual, generates TLDR summaries, and analyses sentiment across US and UK news sources. Features a Good News filter, content guardrails for distressing topics, and country/category filters. No ads, no tracking, no account required.',
    topics: ['Azure OpenAI', 'AI Search', 'Python', 'Streamlit'],
    language: 'Python',
    category: 'ai',
    links: { github: 'https://github.com/ThomasJButler/NewsPerspective' },
    highlights: ['AI headline rewriting', 'Sentiment analysis', 'Good News filter', 'No ads, no tracking'],
  },
  {
    id: 'mastering-ai-portfolio',
    name: 'AI & Agents Portfolio',
    description: 'Portfolio of AI projects from the Codecademy 6-week bootcamp demonstrating LangChain, RAG, and multi-agent architectures.',
    topics: ['Next.js', 'TypeScript', 'Tailwind', 'Anime.js'],
    language: 'TypeScript',
    category: 'ai',
    links: { demo: 'https://agenticaiprojectsportfolio.vercel.app/', github: 'https://github.com/ThomasJButler/AgenticAICoursePortfolio' },
  },
  {
    id: 'commercial-portfolio',
    name: 'Commercial Portfolio',
    description: 'Professional commercial portfolio showcasing 3+ years of full-stack development. Built with React v2.0 architecture.',
    topics: ['React', 'TypeScript', 'Vite', 'Node.js'],
    language: 'React',
    category: 'web',
    links: { github: 'https://github.com/ThomasJButler/commercial-portfolio-react', demo: 'https://www.thomasjbutler.me/' },
    featured: true,
  },
  {
    id: 'lfc-news-reddit',
    name: 'LFC News App',
    description: 'Distraction-free Reddit viewer for LFC content. No ads, no tracking, three kit themes, spicy meter for trending posts.',
    longDescription: 'All the LFC content, none of the noise. Pulls posts and comments directly from r/LiverpoolFC and displays them in a clean interface. Features filter by category (match days, transfers, images, videos), threaded comments with inline media, three kit themes (Anfield Red, Away Cream, Keeper Green), a spicy meter for trending posts, and search across everything.',
    topics: ['React', 'Redux', 'Reddit API'],
    language: 'JavaScript',
    category: 'web',
    links: { github: 'https://github.com/ThomasJButler/LFC-News-Reddit-App', demo: 'https://lfc-news-reddit-app.vercel.app/' },
    highlights: ['Distraction-free Reddit reader', 'Three kit themes', 'Threaded comments with inline media', 'No account or ads needed'],
  },
  {
    id: 'dotnet-react-calendar',
    name: '.NET/React Calendar',
    description: 'Full-stack calendar app with .NET Core 9 FastEndpoints backend and React frontend.',
    topics: ['.NET', 'React', 'C#', 'Fast Endpoints'],
    language: 'C#',
    category: 'web',
    links: { demo: 'https://dotnet-react-calendar.vercel.app/', github: 'https://github.com/ThomasJButler/Dotnet-React-Calendar' },
  },
  {
    id: 'css-showcase',
    name: 'CSS Learning Showcase',
    description: 'Interactive CSS reference with 30+ pages of live demos, playgrounds, and modern features like container queries and :has().',
    longDescription: 'Comprehensive CSS learning resource built with Next.js and shadcn/ui. Features 30+ pages of live demos, interactive playgrounds, and real code examples covering everything from basic selectors to modern features like container queries, :has() selector, scroll-driven animations, and colour spaces.',
    topics: ['CSS', ':has()', 'Container Queries', 'Responsive'],
    language: 'CSS',
    category: 'web',
    links: { demo: 'https://thomasjbutler.github.io/css-showcase/', github: 'https://github.com/ThomasJButler/css-showcase' },
  },
  {
    id: 'matrix-arcade',
    name: 'The Matrix Arcade',
    description: 'Collection of 6 Matrix-themed arcade games: CTRL-S, Snake, Vortex Pong, Matrix Cloud, Matrix Invaders, and Metris.',
    longDescription: 'A collection of 6 Matrix-themed arcade games built with React 18 and TypeScript. Includes CTRL-S (text adventure), Snake Classic, Vortex Pong, Matrix Cloud, Matrix Invaders, and Metris. Features PWA support, Web Audio API for sound effects, and Framer Motion animations — all wrapped in an authentic Matrix green-on-black aesthetic.',
    topics: ['React', 'Canvas API', 'Vite', 'Game Dev'],
    language: 'JavaScript',
    category: 'games',
    links: { demo: 'https://the-matrix-arcade.vercel.app/', github: 'https://github.com/ThomasJButler/The-Matrix-Arcade' },
    featured: true,
    status: 'completed',
    highlights: ['6 playable arcade games', 'React 18 + TypeScript + PWA', 'Web Audio API sound effects', 'Authentic Matrix aesthetic'],
  },
  {
    id: 'bigbang-gallery',
    name: 'Big Bang Canvas',
    description: 'Responsive gallery of 50+ AI-generated cosmic artworks with 3D tilt effects, custom cursor, and keyboard navigation.',
    topics: ['Canvas', 'Animation', 'Creative', 'Design'],
    language: 'JavaScript',
    category: 'creative',
    links: { demo: 'https://thomasjbutler.github.io/bigbang-gallery/', github: 'https://github.com/ThomasJButler/bigbang-gallery' },
  },
  {
    id: 'python-projects',
    name: 'Python Projects Collection',
    description: 'Collection of Python hobby projects: mathematical tools, climate visualisation, AI assistants, and interactive games.',
    topics: ['Python', 'Algorithms', 'ML', 'Games'],
    language: 'Python',
    category: 'personal',
    links: { github: 'https://github.com/ThomasJButler/PythonProjects' },
  },
  {
    id: 'version-timetravel',
    name: 'Version TimeTravel',
    description: 'Interactive timeline showcasing 9 portfolio versions from static HTML to modern React, with responsive preview viewer.',
    topics: ['Timeline', 'Interactive', 'History'],
    language: 'JavaScript',
    category: 'personal',
    links: { demo: 'https://thomasjbutler.github.io/version-timetravel/', github: 'https://github.com/ThomasJButler/version-timetravel' },
  },
];

export const categories = [
  { id: 'all', label: 'All' },
  { id: 'ai', label: 'AI & ML' },
  { id: 'web', label: 'Web' },
  { id: 'games', label: 'Games' },
  { id: 'creative', label: 'Creative' },
  { id: 'personal', label: 'Personal' },
] as const;
