name: Generate Snake

on:
  schedule:
    # Runs at 12:00 UTC daily
    - cron: "0 12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ThomasJButler
          outputs: |
            snake/github-contribution-grid-snake.svg
            snake/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: output
          add: 'snake'
          message: 'Generate contribution snake'
          default_author: github_actions