name: Generate Snake

on:
  schedule:
    # Runs at 12:00 UTC daily
    - cron: "0 12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ThomasJButler
          outputs: |
            snake/github-contribution-grid-snake.svg
            snake/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake to output branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -B output
          git add snake/
          git commit -m "Generate contribution snake" || exit 0
          git push --force origin output